version = "Two"
use_field_init_shorthand = true
max_width = 100

unstable_features = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
overflow_delimited_expr = true
condense_wildcard_suffixes = true
reorder_impl_items = true
